language: python
os: linux
dist: xenial
python:
  - "3.7"
  - "3.8"
  - "3.9"
env:
  - DJANGO=3.1.8 DB=sqlite
  - DJANGO=3.2.0 DB=sqlite
install:
  - pip install -r requirements-dev.txt
script:
  - coverage run --source='./src/ensembl' ./src/manage.py test ensembl.production.webhelp.tests
