language: python
os: linux
dist: xenial
python:
  - "3.7"
  - "3.8"
env:
  - DEBUG=f
install:
  - pip install -r requirements-dev.txt
script:
  - coverage run --source='./src/ensembl' ./src/manage.py test ensembl.production.webhelp.tests
