language: python
os: linux
dist: xenial
python:
  - "3.8"
  - "3.9"
env:
  - DB=sqlite
install:
  - pip install -r requirements-dev.txt
script:
  - coverage run --source='./src/ensembl' ./src/manage.py test ensembl.production.webhelp.tests
