# Generated by Django 3.1.7 on 2021-03-18 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ensembl.production.djcore.fields
import ensembl.production.djcore.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('help_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('keyword', ensembl.production.djcore.fields.SizedTextField(blank=True, null=True, size_class=1)),
                ('data', models.TextField()),
                ('status', ensembl.production.djcore.fields.EnumField(choices=[('draft', 'Draft'), ('live', 'Live'), ('dead', 'Dead')])),
                ('helpful', models.IntegerField(blank=True, null=True)),
                ('not_helpful', models.IntegerField(blank=True, null=True)),
                ('created_by', ensembl.production.djcore.models.SpanningForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='helprecord_created_by', related_query_name='helprecord_creates', to=settings.AUTH_USER_MODEL)),
                ('modified_by', ensembl.production.djcore.models.SpanningForeignKey(blank=True, db_column='modified_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='helprecord_modified_by', related_query_name='helprecord_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'help_record',
            },
        ),
        migrations.CreateModel(
            name='FaqRecord',
            fields=[
            ],
            options={
                'verbose_name': 'FAQ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ensembl_website.helprecord',),
        ),
        migrations.CreateModel(
            name='LookupRecord',
            fields=[
            ],
            options={
                'verbose_name': 'Lookup',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ensembl_website.helprecord',),
        ),
        migrations.CreateModel(
            name='MovieRecord',
            fields=[
            ],
            options={
                'verbose_name': 'Movie',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ensembl_website.helprecord',),
        ),
        migrations.CreateModel(
            name='ViewRecord',
            fields=[
            ],
            options={
                'verbose_name': 'Page',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ensembl_website.helprecord',),
        ),
        migrations.CreateModel(
            name='HelpLink',
            fields=[
                ('help_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_url', ensembl.production.djcore.fields.SizedTextField(null=True, size_class=1)),
                ('help_record', models.OneToOneField(blank=True, db_column='help_record_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='ensembl_website.viewrecord')),
            ],
            options={
                'db_table': 'help_link',
            },
        ),
    ]
